version: "1"
services:
  api: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true # コンテナの永続化
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/app # マウントディレクトリ
    depends_on:
      db:
        condition: service_healthy # dbが起動してからapiを起動する
  db:
    image: postgres:13.5-alpine3.15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      # - $PWD/docker/initdb:/docker-entrypoint-initdb.d
      - $PWD/docker/db:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      timeout: 10s
      retries: 10
