version: "3.8"
services:
  api: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true # コンテナの永続化
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./:/go/src/app # マウントディレクトリ
    depends_on:
      db:
        condition: service_healthy # dbが起動してからapiを起動する
  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
  migrate:
    image: migrate/migrate:v4.18.1
    volumes:
      - ./migrations:/migrations
    working_dir: /migrations
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data: # 名前付きボリューム
